# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47d865105cbdc37170f5bfaa1bda4d530d97581a6452af717aa0746c75c4df528a4b3760e5545f91576609261c01cf528fc6e448f502ad9f49ab8e264594d9f1

test:
  secret_key_base: 1d8f6abf5053fb90d6d0913d1fbdb2eb8890e9c18318199a8982ef22a8f7b1d31f3e01bcadb86e06db0b69e492d5fe20f12898f1eb3c53f13e9281ca0cf0848d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
